### ISSUE TITLE
How to access WebSocket Video Stream?

### ISSUE THREAD

**Issue by kjw8041** [maruel/go-lepton#2]
Hello,

I am new to golang, and I am trying to integrate your code in my project. I have followed the instructions provided, and I can successfully output the lepton -query command. However, when I run lepton, I receive the following (after some time):
$ lepton
Status.CameraStatus: SystemReady
Status.CommandCount: 0
Serial:              0x12345
Uptime:              48m56.275s
Temperature:         30.75°C
Temperature housing: 26.34°C
Telemetry:           Enabled
TelemetryLocation:   Header
FCCMode.FFCShutterMode:          FFCShutterModeExternal
FCCMode.ShutterTempLockoutState: ShutterTempLockoutStateInactive
FCCMode.VideoFreezeDuringFFC:    Enabled
FCCMode.FFCDesired:              Enabled
FCCMode.ElapsedTimeSinceLastFFC: 48m56.285s
FCCMode.DesiredFFCPeriod:        5m0s
FCCMode.ExplicitCommandToOpen:   Disabled
FCCMode.DesiredFFCTempDelta:     3.00°K
FCCMode.ImminentDelay:           52

frames: 110 good 218 duped; lines:20763 good 194442 discard 0 badsync 331 broken; 0 fail 1 resets; 0 HTTP Imgs 13.0s

Is this the correct output that I should be seeing? Also, How do I access the video stream in the Websocket?

**Comment by maruel** [comment]
The frames are mostly good. You need to enable the web server then connect via a web browser. Use lepton -help for more information.
